# Generated by Django 4.2.1 on 2023-05-22 10:28

from django.db import migrations, models

import trojstenid.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_file",
            field=models.ImageField(
                blank=True, upload_to=trojstenid.users.models.user_avatar_name
            ),
        ),
    ]
