# Generated by Django 4.2.1 on 2023-05-22 21:49

from django.db import migrations

import trojstenid.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_file",
            field=trojstenid.users.models.ImageField(
                blank=True, upload_to=trojstenid.users.models.user_avatar_name
            ),
        ),
    ]
