# Generated by Django 4.2.5 on 2023-12-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_application_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
            ),
        ),
    ]
