# Generated by Django 5.0.1 on 2024-01-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_application_allowed_origins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="auth.group",
            ),
        ),
    ]
