# Generated by Django 5.2.4 on 2026-01-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_application_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="push_urls",
            field=models.TextField(blank=True),
        ),
    ]
