# Generated by Django 5.2.4 on 2026-02-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_application_push_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="now_known_as",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previously_known_as",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
