# Generated by Django 5.2.4 on 2026-07-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trojstenid.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_now_known_as"),
    ]

    operations = [
        migrations.CreateModel(
            name="WifiPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[trojstenid.users.models.UsernameValidator()],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("allowed_callers", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
