# Generated by Django 5.2 on 2025-06-17 20:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("short", models.CharField(max_length=128)),
                (
                    "years",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eduid", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("address", models.CharField(blank=True, max_length=256)),
                ("is_selectable", models.BooleanField(default=True)),
                ("types", models.ManyToManyField(to="trojstenid_schools.schooltype")),
            ],
        ),
        migrations.CreateModel(
            name="UserSchoolRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("start_year", models.PositiveIntegerField(default=0)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="trojstenid_schools.school",
                    ),
                ),
                (
                    "school_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="trojstenid_schools.schooltype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
