# Generated by Django 5.2 on 2025-06-17 19:39

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trojstenid_schools", "0001_initial"),
    ]

    operations = [
        UnaccentExtension(),
    ]
