# Generated by Django 5.2 on 2025-06-18 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trojstenid_schools", "0002_auto_20250617_2139"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["eduid", "name"]},
        ),
        migrations.AlterModelOptions(
            name="schooltype",
            options={"ordering": ["identifier"]},
        ),
        migrations.AlterModelOptions(
            name="userschoolrecord",
            options={"ordering": ["user_id", "start_date"]},
        ),
    ]
