# Generated by Django 5.2.16 on 2026-09-06 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trojstenid_schools",
            "0003_alter_school_options_alter_schooltype_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userschoolrecord",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userschoolrecord",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userschoolrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userschoolrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
