name: pre-commit + migration check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: pre-commit/action@v3.0.1

  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install Dependencies
      run: uv sync --locked

    - name: Test for missing migrations
      run: uv run python manage.py makemigrations --check
      env:
        DEBUG: True
        DATABASE_URL: "sqlite://:memory:"
        TROJSTEN_LOGIN_CLIENT: ""
        TROJSTEN_LOGIN_SECRET: ""
        RECAPTCHA_PUBLIC: ""
        RECAPTCHA_PRIVATE: ""
        OIDC_KEY: ""
