name: pre-commit + migration check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.0

  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: "pipenv"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv sync
    - name: Test for missing migrations
      run: pipenv run python manage.py makemigrations --check
      env:
        DEBUG: True
        DATABASE_URL: "sqlite://:memory:"
        TROJSTEN_LOGIN_CLIENT: ""
        TROJSTEN_LOGIN_SECRET: ""
        RECAPTCHA_PUBLIC: ""
        RECAPTCHA_PRIVATE: ""
        OIDC_KEY: ""

